In [2]:
import numpy as np

In [3]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [4]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
y

range(0, 5)

In [6]:
list(y)

[0, 1, 2, 3, 4]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)

In [9]:
X_train

array([[2, 3],
       [8, 9],
       [4, 5]])

In [10]:
y_train

[1, 4, 2]

In [11]:
X_test

array([[0, 1],
       [6, 7]])

In [12]:
y_test

[0, 3]

In [13]:
train_test_split(y, shuffle=False)

[[0, 1, 2], [3, 4]]

In [14]:
from sklearn.datasets import load_iris

In [15]:
iris = load_iris()

In [16]:
X = iris.data

In [17]:
y = iris.target

In [18]:
print(X.shape)

(150, 4)


In [19]:
print(y.shape)

(150,)


In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [22]:
print(X_train.shape)

(112, 4)


In [23]:
print(X_test.shape)

(38, 4)


In [24]:
print(y_train.shape)

(112,)


In [25]:
print(y_test.shape)

(38,)


In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [28]:
print(X_test.shape)

(60, 4)


In [29]:
print(y_test.shape)

(60,)


In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [31]:
knn = KNeighborsClassifier(n_neighbors=3)

In [32]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [33]:
y_pred = knn.predict(X_test)


In [34]:
from sklearn import metrics

In [35]:
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667


In [36]:
knn = KNeighborsClassifier(n_neighbors=5)

In [37]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [38]:
y_pred = knn.predict(X_test)

In [39]:
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667
