In [2]:
import numpy as np

In [3]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [4]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
y

range(0, 5)

In [6]:
list(y)

[0, 1, 2, 3, 4]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)

In [9]:
X_train

array([[2, 3],
       [8, 9],
       [4, 5]])

In [10]:
y_train

[1, 4, 2]

In [11]:
X_test

array([[0, 1],
       [6, 7]])

In [12]:
y_test

[0, 3]